package com.message.bulksend.autorespond.tools.sheetconnect

import com.google.firebase.firestore.Exclude

/**
 * Data classes for SheetConnect tools
 */

data class SheetConfig(
    val uid: String = "",
    val sheetApiConnected: Boolean = false,
    val sheetApiLastSetup: String = "",
    val googleSheetConfig: String = "" // Contains token data generated by worker
) {
    @Exclude
    fun toMap(): Map<String, Any> {
        return mapOf(
            "uid" to uid,
            "sheetApiConnected" to sheetApiConnected,
            "sheetApiLastSetup" to sheetApiLastSetup,
            "googleSheetConfig" to googleSheetConfig
        )
    }
}

/**
 * Model representing the metadata fetched from the /sheet/metadata endpoint
 */
data class SheetMetadataResponse(
    val success: Boolean,
    val spreadsheetId: String?,
    val spreadsheetTitle: String?,
    val sheets: List<SheetInfo>?,
    val error: String?
)

data class SheetInfo(
    val sheetName: String,
    val columns: List<String>
)

/**
 * Model representing a generalized request to read sheet data
 */
data class SheetReadRequest(
    val userId: String,
    val spreadsheetUrlOrId: String,
    val range: String
)

/**
 * Model representing a generalized request to write sheet data
 */
data class SheetWriteRequest(
    val userId: String,
    val spreadsheetUrlOrId: String,
    val range: String,
    val values: List<List<Any>> // 2D array of rows -> cols
)

/**
 * Represents a spreadsheet created from within the app, stored for quick access.
 */
data class CreatedSheet(
    val title: String = "",
    val spreadsheetId: String = "",
    val spreadsheetUrl: String = "",
    val createdAt: String = ""
)


/**
 * Model representing the user's field mapping configuration.
 * Maps standard AI Agent fields to actual column names in the Google Sheet.
 */
data class SheetMappingConfig(
    val spreadsheetUrlId: String = "",
    val spreadsheetId: String = "",
    val sheetName: String = "",
    val nameColumn: String = "",
    val phoneColumn: String = "",
    val emailColumn: String = "",
    val notesColumn: String = ""
) {
    @Exclude
    fun toMap(): Map<String, Any> {
        return mapOf(
            "spreadsheetUrlId" to spreadsheetUrlId,
            "spreadsheetId" to spreadsheetId,
            "sheetName" to sheetName,
            "nameColumn" to nameColumn,
            "phoneColumn" to phoneColumn,
            "emailColumn" to emailColumn,
            "notesColumn" to notesColumn
        )
    }
}
